== Interviewing at the Detector Lab

Hello!  I'm delighted to hear that you think some of the projects in my lab sound interesting.  If I have openings available in my group, then the next step is an interview.

The interview will be pretty short (about 20 minutes) and I'd like to be able to talk with you (in person or phone).  I'd recommend writing out responses to the questions below and emailing them to me ahead of time.  My expectation is that after the interview, we'll both take one or two days to consider - would I like to hire you, and would you like to work here?  I'll send you an email within 24 hours with an answer, and you are welcome to take some time to answer back.

== Here are the questions I plan to ask:

* What are your future plans?
* Do you have any questions about this position?
* How many hours per week will you be able to work?  
* How do you approach managing your time commitments when the semester gets busy?
* Working in my group is often very unstructured.  What is your approach to getting work done in this kind of environment?
* If you were to work in my lab, what are your expectations for yourself as a member of the lab?  What are your expectations for me as your advisor?  My (broad) expectations are at https://github.com/det-lab/conduct_code/blob/master/expectations.adoc.  How do yours differ?  Let's figure out how to work together!
* The university conduct code asks all of us to work towards an inclusive and welcoming space.  What does an inclusive space feel like to you?  How have you helped make a space inclusive for others?
* My lab has its own code of conduct (https://github.com/det-lab/conduct_code/blob/master/conduct_code.adoc).  Do you have any questions or concerns about these guidelines?
* Do you have any additional questions for me?

== Here is what I am trying to asses:

* Do I think this student will create one or more useful products over the course of the semester?
* Do I think this student will require more than two hours per week of supervision from me?
* Do I think this student will work well with the group?
* Do I think this student will work in my group for a full semester or more?
* Do I think this student will benefit from and enjoy working on projects available in my group?
